#!/bin/bash
#
# build - compile and optionally install cbftp
#

usage() {
    printf "\nUsage: ./build [-i] [-p prefix] [-u] project [project2 ...]"
    printf "\nWhere:"
    printf "\n\t-i indicates install"
    printf "\n\t-p prefix specifies installation prefix (default ${PREFIX})"
    printf "\n\t-u displays this usage message and exits\n"
    printf "\nNo arguments: build cpftp, configure with prefix=${PREFIX}, build\n"
    exit 1
}

INSTALL=
platform=`uname -s`
if [ "${platform}" == "Darwin" ]
then
  PREFIX=/usr/local
else
  PREFIX=/usr
fi
while getopts "ip:u" flag; do
    case $flag in
        i)
            INSTALL=1
            ;;
        p)
            PREFIX="$OPTARG"
            ;;
        u)
            usage
            ;;
    esac
done
shift $(( OPTIND - 1 ))

[ -f bin/cbftp ] || {
  [ -f /etc/arch-release ] && {
    NCW="src/ui/ncurseswrap.h"
    cp ${NCW} /tmp/nc_save$$
    cat ${NCW} | sed -e "s%ncursesw/curses.h%ncurses.h%" > /tmp/nc$$
    cp /tmp/nc$$ ${NCW}
    rm -f /tmp/nc$$
  }
  make
  [ -f /tmp/nc_save$$ ] && cp /tmp/nc_save$$ ${NCW}
}
chmod +x bin/*
